name: sudoku-project
channels:
  - defaults
dependencies:
    - python
    - tensorflow
    - numpy
    - pandas
    - seaborn
    - matplotlib
    - pylint
    - autopep8
    - notebook
    - keras
    - opencv
    - pip:
        - sklearn